name: Perl CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
      - name: Install developer dependencies
        run: |
          cpanm Test::More
      - run: cpanm --installdeps .
      - run: prove -lv t